const sampleListings = [
  {
    title: "Beachside Shack in Goa",
    description: "Stay just steps away from the Arabian Sea in this colorful beach shack with lively nightlife nearby.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Goa",
    country: "India",
    geometry: { type: "Point", coordinates: [73.8567, 15.2993] },
  },
  {
    title: "Mountain View Cottage in Manali",
    description: "A peaceful Himalayan cottage with stunning views of snow-capped peaks.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    location: "Manali",
    country: "India",
    geometry: { type: "Point", coordinates: [77.1887, 32.2396] },
  },
  {
    title: "Heritage Haveli in Jaipur",
    description: "Experience royal living in a traditional haveli with Rajasthani architecture and culture.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    location: "Jaipur",
    country: "India",
    geometry: { type: "Point", coordinates: [75.7873, 26.9124] },
  },
  {
    title: "Backwater Houseboat in Kerala",
    description: "Sail through serene backwaters in Alleppey on a private luxury houseboat.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Alleppey",
    country: "India",
    geometry: { type: "Point", coordinates: [76.3388, 9.4981] },
  },
  {
    title: "Riverside Retreat in Varanasi",
    description: "A spiritual stay on the ghats of the Ganges River with traditional Indian vibes.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600703145081-331eaa1f0358?auto=format&fit=crop&w=800&q=60",
    },
    price: 1100,
    location: "Varanasi",
    country: "India",
    geometry: { type: "Point", coordinates: [82.9739, 25.3176] },
  },
  {
    title: "Lakeside Palace in Udaipur",
    description: "Stay like royalty in the City of Lakes with stunning palace architecture.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=800&q=60",
    },
    price: 2800,
    location: "Udaipur",
    country: "India",
    geometry: { type: "Point", coordinates: [73.7125, 24.5854] },
  },
  {
    title: "Luxury Tent in Jaisalmer Desert",
    description: "Enjoy a desert safari and camp under the stars in golden sand dunes.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1586953208448-73f291fdfb2e?auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Jaisalmer",
    country: "India",
    geometry: { type: "Point", coordinates: [70.9167, 26.9167] },
  },
  {
    title: "Tea Estate Bungalow in Darjeeling",
    description: "Wake up to misty mornings in a heritage bungalow surrounded by tea plantations.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1615475667650-d7ff28099117?auto=format&fit=crop&w=800&q=60",
    },
    price: 1900,
    location: "Darjeeling",
    country: "India",
    geometry: { type: "Point", coordinates: [88.2627, 27.041] },
  },
  {
    title: "Himalayan Monastery Stay in Leh",
    description: "Stay close to ancient monasteries and experience Ladakh’s culture and landscapes.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600250393924-3f25b433d0a8?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Leh",
    country: "India",
    geometry: { type: "Point", coordinates: [77.5619, 34.1526] },
  },
  {
    title: "Hill Station Villa in Ooty",
    description: "A charming colonial villa surrounded by lush tea gardens and cool mountain air.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "Ooty",
    country: "India",
    geometry: { type: "Point", coordinates: [76.6932, 11.4064] },
  },
  {
    title: "Luxury Apartment in Mumbai",
    description: "Experience the fast-paced city life with Arabian Sea views in South Mumbai.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    location: "Mumbai",
    country: "India",
    geometry: { type: "Point", coordinates: [72.8777, 19.076] },
  },
  {
    title: "IT Hub Studio in Bangalore",
    description: "Modern studio apartment in the Silicon Valley of India with great nightlife.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    location: "Bangalore",
    country: "India",
    geometry: { type: "Point", coordinates: [77.5946, 12.9716] },
  },
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
    geometry: { type: "Point", coordinates: [-118.7798, 34.0259] },
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "New York City",
    country: "United States",
    geometry: { type: "Point", coordinates: [-74.006, 40.7128] },
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=60",
    },
    price: 1000,
    location: "Aspen",
    country: "United States",
    geometry: { type: "Point", coordinates: [-106.8175, 39.1911] },
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Florence",
    country: "Italy",
    geometry: { type: "Point", coordinates: [11.2558, 43.7699] },
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=60",
    },
    price: 800,
    location: "Portland",
    country: "United States",
    geometry: { type: "Point", coordinates: [-122.6765, 45.5231] },
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    location: "Cancun",
    country: "Mexico",
    geometry: { type: "Point", coordinates: [-86.8515, 21.1619] },
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
    },
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
    geometry: { type: "Point", coordinates: [-120.043, 39.0968] },
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?auto=format&fit=crop&w=800&q=60",
    },
    price: 3500,
    location: "Los Angeles",
    country: "United States",
    geometry: { type: "Point", coordinates: [-118.2437, 34.0522] },
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
    geometry: { type: "Point", coordinates: [7.2265, 46.0966] },
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
    geometry: { type: "Point", coordinates: [34.6857, -2.3333] },
  },
  {
    title: "Historic Canal House",
    description: "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Amsterdam",
    country: "Netherlands",
    geometry: { type: "Point", coordinates: [4.9041, 52.3676] },
  },
  {
    title: "Private Island Retreat",
    description: "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?auto=format&fit=crop&w=800&q=60",
    },
    price: 10000,
    location: "Fiji",
    country: "Fiji",
    geometry: { type: "Point", coordinates: [178.065, -17.7134] },
  },
  {
    title: "Cotswolds Country Cottage",
    description: "Enjoy the rolling hills of England in this traditional stone cottage in the Cotswolds.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
    },
    price: 1400,
    location: "Cotswolds",
    country: "United Kingdom",
    geometry: { type: "Point", coordinates: [-1.7201, 51.833] },
  },
  {
    title: "Harborview Apartment",
    description: "Wake up to stunning harbor views in this modern Boston apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1560448075-bb485b1668ec?auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Boston",
    country: "United States",
    geometry: { type: "Point", coordinates: [-71.0589, 42.3601] },
  },
  {
    title: "Balinese Jungle Villa",
    description: "Relax in a luxury villa surrounded by Bali’s lush jungle and rice terraces.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1543349689-9a4d426bee8d?auto=format&fit=crop&w=800&q=60",
    },
    price: 2600,
    location: "Bali",
    country: "Indonesia",
    geometry: { type: "Point", coordinates: [115.1889, -8.4095] },
  },
  {
    title: "Canadian Rockies Lodge",
    description: "Explore Banff National Park while staying in a cozy lodge with mountain views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=800&q=60",
    },
    price: 2300,
    location: "Banff",
    country: "Canada",
    geometry: { type: "Point", coordinates: [-115.5708, 51.1784] },
  },
  {
    title: "Luxury Condo in Miami Beach",
    description: "Enjoy vibrant nightlife and sandy beaches from this Miami luxury condo.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600585154154-18f8f12e9a3a?auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    location: "Miami",
    country: "United States",
    geometry: { type: "Point", coordinates: [-80.1918, 25.7617] },
  },
  {
    title: "Phuket Beach Villa",
    description: "Step out onto the soft sands of Phuket in this luxury beachfront villa.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=60",
    },
    price: 2800,
    location: "Phuket",
    country: "Thailand",
    geometry: { type: "Point", coordinates: [98.3984, 7.8804] },
  },
  {
    title: "Scottish Highlands Castle",
    description: "Live like royalty in a historic castle surrounded by the breathtaking Scottish Highlands.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1610544073650-9c0d8e3c6d92?auto=format&fit=crop&w=800&q=60",
    },
    price: 5000,
    location: "Scottish Highlands",
    country: "United Kingdom",
    geometry: { type: "Point", coordinates: [-4.2026, 57.12] },
  },
  {
    title: "Dubai Marina Apartment",
    description: "Stay in the heart of Dubai with stunning views of the Marina skyline.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1523731407965-2430cd12f5e4?auto=format&fit=crop&w=800&q=60",
    },
    price: 4500,
    location: "Dubai",
    country: "United Arab Emirates",
    geometry: { type: "Point", coordinates: [55.2708, 25.2048] },
  },
  {
    title: "Montana Ranch Cabin",
    description: "Escape to the wide-open spaces of Montana in a rustic ranch cabin.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    },
    price: 1600,
    location: "Montana",
    country: "United States",
    geometry: { type: "Point", coordinates: [-110.3626, 46.8797] },
  },
  {
    title: "Mykonos Cliffside Villa",
    description: "Enjoy stunning sunsets over the Aegean Sea from this luxurious villa.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=60",
    },
    price: 4200,
    location: "Mykonos",
    country: "Greece",
    geometry: { type: "Point", coordinates: [25.3289, 37.4467] },
  },
  {
    title: "Eco Lodge in Costa Rica",
    description: "Reconnect with nature in a sustainable eco lodge in the Costa Rican rainforest.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1558981852-426c6c22a050?auto=format&fit=crop&w=800&q=60",
    },
    price: 1900,
    location: "Costa Rica",
    country: "Costa Rica",
    geometry: { type: "Point", coordinates: [-84.0739, 9.7489] },
  },
  {
    title: "Charleston Historic Home",
    description: "Stay in a charming historic home in the heart of Charleston.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600585154164-3b9a3a6be912?auto=format&fit=crop&w=800&q=60",
    },
    price: 2100,
    location: "Charleston",
    country: "United States",
    geometry: { type: "Point", coordinates: [-79.9311, 32.7765] },
  },
  {
    title: "Tokyo City Apartment",
    description: "Experience the energy of Tokyo while staying in a modern city apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505826759031-84d1134ba5c5?auto=format&fit=crop&w=800&q=60",
    },
    price: 3200,
    location: "Tokyo",
    country: "Japan",
    geometry: { type: "Point", coordinates: [139.6917, 35.6895] },
  },
  {
    title: "New Hampshire Lake House",
    description: "Spend your summer at a tranquil New Hampshire lake house.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1525097487452-6278ff080c31?auto=format&fit=crop&w=800&q=60",
    },
    price: 1700,
    location: "New Hampshire",
    country: "United States",
    geometry: { type: "Point", coordinates: [-71.5724, 43.1939] },
  },
  {
    title: "Overwater Bungalow in Maldives",
    description: "Sleep above the turquoise waters in a luxurious overwater bungalow.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    },
    price: 7500,
    location: "Maldives",
    country: "Maldives",
    geometry: { type: "Point", coordinates: [73.2207, 3.2028] },
  }
];

module.exports = { data: sampleListings };
